keys:
  - &endurance age16nzr436h3pf8akpwtgm3ur5sgh962qe95shne0lhn08serll9ykqvf35a9
  - &tars age1mtn2a4264tn4sqw4s6lwrpdy6uk55wt2dwaecz5k7pfxunmdruksn7j7k9
  - &gargantua age1c462dzpk5qqathxefu78pq57vn45ypur5f6mx6wrgqdz8pdxs4pqw7883g

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *endurance
          - *tars
          - *gargantua
