cf_dns_api_token: ENC[AES256_GCM,data:Psg4FoHZib6585sOuPKYxDz2menCNfVkfkUolXSM2G76aPHLgU4XdEgDO2OMTJJvcx5jARk=,iv:ynemyHj0ybhEz/FKMYUm/ajiawdEvNuDCttnHeS9Qbo=,tag:ACUyJxJWgsQ2iI6VnoM6ww==,type:str]
cf_email: ENC[AES256_GCM,data:oDbrmvjLToaJss5RrpRo+QLV,iv:BmfEgX0RkMbpc8mwtdPyOMTKu9fz0XRyDbmYz37yp18=,tag:phakVCCN5Ln9QMDOaToUgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXRzNmFuQjg0aWxqc3F1
            TU13bU5SSU8rbzFTSklNMFhmd0VlU3ErUWdvCjFTeU9NU0dUVHY2SFp4V3JITCtT
            UXM2ZW1Mam5rYU92K1Y1ejJXK1VlelEKLS0tIDFVRVc2VTY2V1lpWFU2OHFGY0RX
            QytmK1hTM0Ywa1d1V2o4Y3IzQ0NxYnMKFsrp4PNUyFEng9vcHT0gk2dovyggy9ai
            avhnv1KLpBdu1gd3PBNJXCCR6qtJ7obsoVulxKgB0aRg8MrIW2EiwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nzr436h3pf8akpwtgm3ur5sgh962qe95shne0lhn08serll9ykqvf35a9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeThFNE1qZ00vWktZaVBM
            am1BbjZwUXg3U3JDN3M2Z3diQnhtOE5Qc2drCjJQZHlCNVdwZy9hWjVkZXBZZU9B
            aEpiaVJEYm13Q2U1aW5TUEw5UksrUnMKLS0tIG8wU0h2T1Y1Rk9BcWVBdUdJT0ZX
            RS92eVRIaUhWZ0FsbDgrMForQldZOU0KIsm5QVYkrw9LMculGvfXplmwsb0xEgSN
            YhY27zy97SRRQB61UVnieQpGJ0oE5PBO+JXX3b+g5xMh/0KE9vYvxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7ju4hc479r38rn5xcthn44efkjvxc988q7y78dkd9ee8pah2ptq26dqn3
    lastmodified: "2026-08-18T01:14:25Z"
    mac: ENC[AES256_GCM,data:K04cF2CH+nO4O/rT1pBqdUfnwtAPu0+4IrGkbeDV4A0pnTjr/RxCKtYZIvKZNG5rYN0zJKb93Xn3BbplkgB2+BqIW0hZRJUM/tnAoAGd3EBW3rcMfsMU4GBXZ46XT70UytfUYVybaC1MwOCurmJPOuQMCdJpza+KzZJN/CLjxl0=,iv:396UyvrkSDOaGQ+IqBta+Zlj3emYImN7b7JsqZ14APA=,tag:aM0R5tTuM413ohPlnuBhTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
